### ISSUE TITLE
Crash when the apiVersion is uninitialized at game start (usually when the server is down or network slow)

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/Unciv#29]
**Platform:** Desktop
**Version:** 4.6.5 (Build 855)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

**Message:**
```
kotlin.UninitializedPropertyAccessException: lateinit property apiVersion has not been initialized
	at com.unciv.logic.multiplayer.OnlineMultiplayer.getApiVersion(OnlineMultiplayer.kt:88)
	at com.unciv.ui.popups.options.MultiplayerTabKt.addMultiplayerServerOptions(MultiplayerTab.kt:157)
	at com.unciv.ui.popups.options.MultiplayerTabKt.multiplayerTab(MultiplayerTab.kt:102)
	at com.unciv.ui.popups.options.OptionsPopup.<init>(OptionsPopup.kt:100)
	at com.unciv.ui.screens.basescreen.BaseScreen.openOptionsPopup(BaseScreen.kt:173)
	at com.unciv.ui.screens.basescreen.BaseScreen.openOptionsPopup$default(BaseScreen.kt:172)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$optionsTable$1.invoke(MainMenuScreen.kt:183)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$optionsTable$1.invoke(MainMenuScreen.kt:182)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$getMenuButton$1.invoke(MainMenuScreen.kt:103)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$getMenuButton$1.invoke(MainMenuScreen.kt:101)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$onActivation$1.invoke(Scene2dExtensions.kt:194)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$onActivation$1.invoke(Scene2dExtensions.kt:192)
	at com.unciv.ui.components.extensions.ActorAttachments.activate(Scene2dExtensions.kt:140)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt.activate(Scene2dExtensions.kt:183)
	at com.unciv.ui.components.extensions.ActorAttachments$addActivationAction$2.clicked(Scene2dExtensions.kt:151)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:18)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:90)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:90)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:90)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:80)

```

**Comment by CrsiX** [comment]
Not reproducible with the current version
