### ISSUE TITLE
When logging in, some network errors are not yet handled (endpoint /api/v2/auth/login)

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/Unciv#53]
**Platform:** Desktop
**Version:** 4.6.5 (Build 855)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

**Message:**
```
com.unciv.logic.multiplayer.apiv2.UncivNetworkException: An unexpected network error occurred.
	at com.unciv.logic.multiplayer.apiv2.EndpointImplementationsKt.request(EndpointImplementations.kt:99)
	at com.unciv.logic.multiplayer.apiv2.EndpointImplementationsKt.access$request(EndpointImplementations.kt:1)
	at com.unciv.logic.multiplayer.apiv2.EndpointImplementationsKt$request$1.invokeSuspend(EndpointImplementations.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.ktor.client.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=http://127.0.0.1:8080/api/v2/auth/login, connect_timeout=3000 ms]
	at io.ktor.client.plugins.HttpTimeoutKt.ConnectTimeoutException(HttpTimeout.kt:213)
	at io.ktor.client.plugins.HttpTimeoutKt.ConnectTimeoutException$default(HttpTimeout.kt:210)
	at io.ktor.client.engine.cio.Endpoint.getTimeoutException(Endpoint.kt:217)
	at io.ktor.client.engine.cio.Endpoint.connect(Endpoint.kt:206)
	at io.ktor.client.engine.cio.Endpoint.access$connect(Endpoint.kt:23)
	at io.ktor.client.engine.cio.Endpoint$connect$1.invokeSuspend(Endpoint.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by CrsiX** [comment]
This should be fixed now. Re-open if it happens again.
