### ISSUE TITLE
Backward compatibility with APIv1 is broken

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/Unciv#57]
```
2023-05-10T20:43:20.876734Z [threadpool-nondaemon-3] [SimpleHttp] Error during HTTP request | java.io.IOException: Server returned HTTP response code: 400 for URL: https://uncivserver.xyz/files/fbd15ed4-c474-46b8-9d3c-30bcf017e839
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendRequest(SimpleHttp.kt:59)
	at com.unciv.logic.multiplayer.storage.UncivServerFileStorage.saveGameData(UncivServerFileStorage.kt:14)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerFiles.tryUploadGame(OnlineMultiplayerFiles.kt:67)
	at com.unciv.logic.multiplayer.OnlineMultiplayer.createGame(OnlineMultiplayer.kt:210)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invokeSuspend(NewGameScreen.kt:308)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.startNewGame(NewGameScreen.kt:279)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.access$startNewGame(NewGameScreen.kt:49)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$5.invokeSuspend(NewGameScreen.kt:213)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$5.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$5.invoke(NewGameScreen.kt)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2023-05-10T20:43:20.877207Z [threadpool-nondaemon-3] [SimpleHttp] Returning error message [Bad Request!]
2023-05-10T20:43:20.877366Z [threadpool-nondaemon-3] [UncivServerFileStorage$saveGameData] Error from UncivServer during save: Bad Request!
2023-05-10T20:43:20.877924Z [threadpool-nondaemon-3] [NewGameScreen$startNewGame] [ERROR] Error while creating game | java.lang.Exception: Bad Request!
	at com.unciv.logic.multiplayer.storage.UncivServerFileStorage$saveGameData$2.invoke(UncivServerFileStorage.kt:20)
	at com.unciv.logic.multiplayer.storage.UncivServerFileStorage$saveGameData$2.invoke(UncivServerFileStorage.kt:14)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendRequest(SimpleHttp.kt:67)
	at com.unciv.logic.multiplayer.storage.UncivServerFileStorage.saveGameData(UncivServerFileStorage.kt:14)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerFiles.tryUploadGame(OnlineMultiplayerFiles.kt:67)
	at com.unciv.logic.multiplayer.OnlineMultiplayer.createGame(OnlineMultiplayer.kt:210)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invokeSuspend(NewGameScreen.kt:308)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.startNewGame(NewGameScreen.kt:279)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.access$startNewGame(NewGameScreen.kt:49)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$5.invokeSuspend(NewGameScreen.kt:213)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$5.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$5.invoke(NewGameScreen.kt)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by CrsiX** [comment]
This only affects https://uncivserver.xyz, all other tested APIv1 servers don't have this issue. The reply of the server is just the text `Bad Request!` along a `400` response. It's hard to debug further, since the very same client version works with all other APIv1 servers.

**Comment by CrsiX** [comment]
The server at https://replit.uncivserver.xyz yields the response `{"statusCode":500,"code":"Z_DATA_ERROR","error":"Internal Server Error","message":"incorrect header check"}` along a `500` response.

**Comment by CrsiX** [comment]
It turns out, that those two implementations **enforced** base64-encoded content. Now the client enforces the zipped and base64-encoded upload of game states to all non-APIv2 servers.
