### ISSUE TITLE
WebSocket friend event de-serialization fails

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/Unciv#7]
A friendship event looks like this:

```
{"type":"friendshipChanged","content":{"friend":{"uuid":"e3ad78d7-78e0-427b-8afb-44f25ac4e62d","username":"666","display_name":"666"},"event":"accepted"}}
```

De-serialization of this event doesn't work yet. It fails with an exception: 

```
kotlinx.serialization.SerializationException: com.unciv.logic.multiplayer.apiv2.FriendshipEvent does not contain element with name 'accepted'
```

<details>

```
	at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow(JsonNamesMap.kt:63)
	at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow$default(JsonNamesMap.kt:60)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedEnum(TreeJsonDecoder.kt:87)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedEnum(TreeJsonDecoder.kt:36)
	at kotlinx.serialization.internal.TaggedDecoder.decodeEnum(Tagged.kt:234)
	at kotlinx.serialization.internal.EnumSerializer.deserialize(Enums.kt:113)
	at kotlinx.serialization.internal.EnumSerializer.deserialize(Enums.kt:79)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:280)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:297)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:280)
	at com.unciv.logic.multiplayer.apiv2.FriendshipChanged$$serializer.deserialize(WebSocketStructs.kt:113)
	at com.unciv.logic.multiplayer.apiv2.FriendshipChanged$$serializer.deserialize(WebSocketStructs.kt:113)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:280)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:297)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:280)
	at com.unciv.logic.multiplayer.apiv2.FriendshipChangedMessage$$serializer.deserialize(WebSocketStructs.kt:263)
	at com.unciv.logic.multiplayer.apiv2.FriendshipChangedMessage$$serializer.deserialize(WebSocketStructs.kt:263)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52)
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:25)
	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:115)
	at kotlinx.serialization.json.JsonContentPolymorphicSerializer.deserialize(JsonContentPolymorphicSerializer.kt:93)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:95)
	at com.unciv.logic.multiplayer.apiv2.ApiV2.handleWebSocket(ApiV2.kt:274)
	at com.unciv.logic.multiplayer.apiv2.ApiV2.access$handleWebSocket(ApiV2.kt:34)
	at com.unciv.logic.multiplayer.apiv2.ApiV2$handleWebSocket$1.invokeSuspend(ApiV2.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

**Comment by CrsiX** [comment]
Fixed via 20683c920c7d20efde9d5047242fc114f9d2c8be
