### ISSUE TITLE
V1 Incompatibility: can download, but not upload existing game

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/Unciv#82]
**Version**
[v5.0-alpha2](https://github.com/hopfenspace/Unciv/releases/tag/v5.0-alpha2)

**Server**
https://uncivserver.xyz

**Describe the bug**
Any existing game can be loaded but not uploaded.

![](https://user-images.githubusercontent.com/46617994/246426602-4d71c0b4-079c-45f1-9308-8879a921a817.png)

**To Reproduce**
Unknown. Investigating ...

Originally reported by @touhidurrr

**Comment by CrsiX** [comment]
When uploading a new game from the `NewGameScreen`, it fails with the following error: 

```
2023-06-18T09:28:39.823125Z [threadpool-nondaemon-0] [SimpleHttp] Returning error message [Bad Request!]
2023-06-18T09:28:39.823359Z [threadpool-nondaemon-0] [UncivServerFileStorage$saveGameData] Error from UncivServer during save: Bad Request!
2023-06-18T09:28:39.823876Z [threadpool-nondaemon-0] [NewGameScreen$startNewGame] [ERROR] Error while creating game | java.lang.Exception: Bad Request!
	at com.unciv.logic.multiplayer.storage.UncivServerFileStorage$saveGameData$2.invoke(UncivServerFileStorage.kt:20)
	at com.unciv.logic.multiplayer.storage.UncivServerFileStorage$saveGameData$2.invoke(UncivServerFileStorage.kt:14)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendRequest(SimpleHttp.kt:67)
	at com.unciv.logic.multiplayer.storage.UncivServerFileStorage.saveGameData(UncivServerFileStorage.kt:14)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerFiles.tryUploadGame(OnlineMultiplayerFiles.kt:67)
	at com.unciv.logic.multiplayer.OnlineMultiplayer.createGame(OnlineMultiplayer.kt:210)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invokeSuspend(NewGameScreen.kt:308)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.startNewGame(NewGameScreen.kt:279)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.access$startNewGame(NewGameScreen.kt:49)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$5.invokeSuspend(NewGameScreen.kt:213)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$5.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$5.invoke(NewGameScreen.kt)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by CrsiX** [comment]
Probably duplicate of #57.
