### ISSUE TITLE
Android: currently unknown instant app crash

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/Unciv#85]
I have no logs or other information (empty logcat), but the app crashes instantly on my Android.

### Confirmed broken versions

- basically everything in the last two weeks™
- 118292f83fa84471d76f777bb311e108e0237fb2
- 1db199a69a07b752ec303018a80646f1d7caa8f8
- 23d3d0d65a4fd686b777273b3492c291d7dab461
- f0444f53591a5086be551addfb66a1b797ee4409
- 7f7134f6638c9945372795c5265c65109016b96e
- f0444f53591a5086be551addfb66a1b797ee4409
- 8d4d7dc1309cec800713f81369bfadfea916e10a T2b

### Working versions

- ef3152ec3d17ffc5054400e1da1f2fdac4ff77cf T2a
- f68ff4c8f3e692de203ab98b4dedea1067ef663b
- c0abe0dd7f32b85599478c2e51381dff3401899f
- 6a8f4914b8839f5660f8df7916ec929c6e5d6914

### Conclusion

Something changed here which now breaks the Android app:
ef3152ec3d17ffc5054400e1da1f2fdac4ff77cf..8d4d7dc1309cec800713f81369bfadfea916e10a

### Debugging

Indeed, after some debugging, I now have a stack trace:
```
Error during onResume/disableReconnecting of com.unciv.app.AndroidLauncher@e74ad49: kotlin.UninitializedPropertyAccessException: lateinit property onlineMultiplayer has not been initialized
Message: lateinit property onlineMultiplayer has not been initialized
kotlin.UninitializedPropertyAccessException: lateinit property onlineMultiplayer has not been initialized
	at com.unciv.UncivGame.getOnlineMultiplayer(UncivGame.kt:132)
	at com.unciv.app.AndroidLauncher.onResume(AndroidLauncher.kt:103)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1564)
	at android.app.Activity.performResume(Activity.java:8473)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4760)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4803)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

This means, I need a check on initialization of that property first.

**Comment by CrsiX** [comment]
This has been addressed and should be solved.
